M48
; DRILL file {KiCad (6.99.0-1006-g2560c8f31b)} date 2022 March 06, Sunday 12:20:55
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-06T12:20:55+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-1006-g2560c8f31b)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1299
%
G90
G05
T1
X4.033Y-4.6473
X6.7019Y-4.6473
X6.7047Y-3.1198
T2
X4.033Y-3.1198
T0
M30
