M48
; DRILL file {KiCad (6.99.0-1533-gf0f33ef1d3)} date 2022 April 06, Wednesday 09:11:24
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-06T09:11:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-1533-gf0f33ef1d3)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1299
%
G90
G05
T1
X4.033Y-4.6473
X6.7019Y-4.6473
X6.7047Y-3.1198
T2
X4.033Y-3.1198
T0
M30
